name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Dependencies
      run: |
        composer install --no-dev --optimize-autoloader
        npm install
        npm run build

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

        # Test SSH connection
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} "echo 'SSH connection successful'"

    - name: Deploy to VPS
      if: success()
      run: |
        rsync -avz --delete -e "ssh -i ~/.ssh/deploy_key" \
          --exclude='.git*' \
          --exclude='node_modules' \
          --exclude='tests' \
          --exclude='.env' \
          --exclude='storage/framework/cache/*' \
          --exclude='storage/framework/sessions/*' \
          --exclude='storage/framework/views/*' \
          ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }}:/var/www/talentbridge

    - name: Post Deploy Commands
      run: |
        ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} "cd /var/www/talentbridge && \
          php artisan storage:link && \
          php artisan migrate --force && \
          php artisan optimize:clear && \
          php artisan config:cache && \
          php artisan route:cache && \
          php artisan view:cache && \
          chown -R www-data:www-data /var/www/talentbridge"
