- name: Configure SSH
  run: |
    mkdir -p ~/.ssh/
    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
    chmod 600 ~/.ssh/deploy_key
    ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    # Test SSH connection
    ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HOST }} "echo 'SSH connection successful'"

- name: Deploy to VPS
  if: success()
  run: |
    rsync -avz --delete -e "ssh -i ~/.ssh/deploy_key" \
      --exclude='.git*' \
      --exclude='node_modules' \
      --exclude='tests' \
      --exclude='.env' \
      --exclude='storage/framework/cache/*' \
      --exclude='storage/framework/sessions/*' \
      --exclude='storage/framework/views/*' \
      ./ ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:/var/www/talentbridge
