name: Run tests
run-name: run-tests

on:
  pull_request:

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP and disable opcache
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Install dependencies
        run: composer install -q --no-interaction

      - name: Prepare environment
        run: cp .env.example .env
        run: php artisan key:generate


      - name: Run tests
        run: php artisan test --compact

